
class DatasetVersion:
    def __init__(self,
                 name: str = None,
                 id: int = None):
        # autogenerated
        self._id = id
        self._name = name

    @property
    def id(self):
        return self._id

    @property
    def name(self):
        return self._name

    def to_json(self):
        to_return = {
            "id": self.id,
            "name": self.name
        }
        return to_return

    @classmethod
    def from_json(cls, json_dict):
        return DatasetVersion(
            id=json_dict['id'],
            name=json_dict['name'])
